[package]
name = "rust_sol"
version = "0.1.0"
authors = ["lsankar4033 <lsankar4033@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
